#!/usr/bin/env python3
"""
Fill Basque translations into the exported POT template.
"""
import re

TRANSLATIONS = {
    # English → Basque
    "# Vendor Bills": "Hornitzaile Fakturak",
    "Academic Term": "Hiruhilekoa",
    "Academic Terms": "Hiruhilekoak",
    "Academic Year": "Ikasturtea",
    "Action Needed": "Ekintza Beharrezkoa",
    "Active": "Aktiboa",
    "Activities": "Jarduerak",
    "Activity": "Jarduera",
    "Additional info": "Informazio gehigarria",
    "Address": "Helbidea",
    "Address Type": "Helbide mota",
    "Admission": "Onarpena",
    "Allowed Department": "Baimendutako Mintegia",
    "Alumni": "Ikasle Ohiak",
    "Approve": "Onartu",
    "Approved": "Onartua",
    "Archived": "Artxibatua",
    "Barcode": "Barra Kodea",
    "Batch": "Taldea",
    "Birth Date": "Jaiotze Data",
    "Birth Date can't be greater than current date!": "Jaiotze data ezin da egungo data baino beranduagoa izan!",
    "Blood Group": "Odol Taldea",
    "Bonafide Certificate": "Ziurtagiria",
    "Both": "Biak",
    "Cancel": "Utzi",
    "Capacity": "Edukiera",
    "Categories": "Kategoriak",
    "Category": "Kategoria",
    "City": "Hiria",
    "Class Room Management": "Gelen Kudeaketa",
    "Class Rooms": "Gelak",
    "Classroom": "Gela",
    "Classroom name must be unique!": "Gelaren izena bakarra izan behar da!",
    "Close": "Itxi",
    "Code": "Kodea",
    "Code should be unique per batch!": "Kodea talde bakoitzeko bakarra izan behar da!",
    "Code should be unique per category!": "Kodea kategoria bakoitzeko bakarra izan behar da!",
    "Code should be unique per classroom!": "Kodea gela bakoitzeko bakarra izan behar da!",
    "Code should be unique per course!": "Kodea ziklo bakoitzeko bakarra izan behar da!",
    "Code should be unique per subject!": "Kodea modulu bakoitzeko bakarra izan behar da!",
    "Color Index": "Kolore Indizea",
    "Companies": "Enpresak",
    "Company": "Enpresa",
    "Company Name": "Enpresa Izena",
    "Company Type": "Enpresa Mota",
    "Compulsory": "Nahitaezkoa",
    "Compulsory Subjects": "Nahitaezko Moduluak",
    "Config Settings": "Konfigurazio Ezarpenak",
    "Contact": "Kontaktua",
    "Country": "Herrialdea",
    "Course": "Zikloa",
    "Course Details": "Zikloaren Xehetasunak",
    "Course not found on student's admission!": "Zikloa ez da ikaslearen matrikulan aurkitu!",
    "Course Registration": "Zikloan Izena Ematea",
    "Create Employee": "Langile Berria Sortu",
    "Create Employee and User of Faculty": "Irakasle eta Erabiltzaile Berria Sortu",
    "Create Parent User": "Guraso Erabiltzailea Sortu",
    "Create Student User": "Ikasle Erabiltzailea Sortu",
    "Create Terms": "Hiruhilekoak Sortu",
    "Create User for selected Faculty(s)": "Hautatutako Irakasle(en)tzat Erabiltzailea Sortu",
    "Create User for selected Student(s)": "Hautatutako Ikasle(en)tzat Erabiltzailea Sortu",
    "Create Users": "Erabiltzaileak Sortu",
    "Created by": "Sortua:",
    "Created on": "Sortze data:",
    "Currency": "Moneta",
    "Dashboard": "Aginte Panela",
    "Date": "Data",
    "Days Before Receipt": "Jasotzea Baino Egun Lehenago",
    "Department": "Mintegia",
    "Department Name": "Mintegiaren Izena",
    "Departments count": "Mintegi kopurua",
    "Display Name": "Bistaratzeko Izena",
    "Draft": "Zirriborroa",
    "Education": "Hezkuntza",
    "Elective": "Aukerako",
    "Elective Subjects": "Aukerako Moduluak",
    "Email": "Helbide elektronikoa",
    "Emergency Contact": "Larrialdi Kontaktua",
    "Employee": "Langilea",
    "Employees": "Langileak",
    "End Date": "Amaiera Data",
    "End Date cannot be set before Start Date.": "Amaiera data ezin da hasiera baino lehenago egon.",
    "Enter Your Valid Mobile Number": "Sartu zure mugikorrak zenbaki balioduna",
    "Evaluation Type": "Ebaluazio Mota",
    "Faculties": "Irakasleak",
    "Faculty": "Irakaslea",
    "Fees": "Tasak",
    "Fees Plan": "Tasen Plana",
    "Female": "Emakumea",
    "Finished": "Amaituta",
    "First Name": "Izena",
    "Format": "Formatua",
    "Gender": "Generoa",
    "General": "Orokorra",
    "Generic": "Generikoa",
    "Get Subjects": "Moduluak Eskuratu",
    "Grade Weightage": "Nota Pisua",
    "Grading": "Kalifikazioa",
    "Group By...": "Taldekatu...",
    "ID": "ID",
    "ID Card Number": "NANaren Zenbakia",
    "Image": "Irudia",
    "Import Template for Batch": "Taldeentzako Inportazio Txantiloia",
    "Import Template for Courses": "Zikloetarako Inportazio Txantiloia",
    "Import Template for Faculties": "Irakasleetarako Inportazio Txantiloia",
    "Import Template for Student Course Details": "Matrikula Xehetasunetarako Inportazio Txantiloia",
    "Import Template for Students": "Ikasleentzako Inportazio Txantiloia",
    "Import Template for Subjects": "Moduluentzako Inportazio Txantiloia",
    "Industry": "Industria",
    "Institute Detail": "Ikastetxearen Xehetasunak",
    "Invoice": "Faktura",
    "Invoices": "Fakturak",
    "Is a Company": "Enpresa da",
    "Is a Parent": "Gurasoa da",
    "Is a Student": "Ikaslea da",
    "Is Follower": "Jarraitzailea da",
    "Job Position": "Lan Posizioa",
    "Language": "Hizkuntza",
    "Last Name": "Abizenak",
    "Last Updated by": "Azken eguneratzailea:",
    "Last Updated on": "Azken eguneratze data:",
    "Line": "Lerroa",
    "Login": "Saioa Hasi",
    "Main Department": "Mintegi Nagusia",
    "Male": "Gizona",
    "Mass Subject Registration": "Modulu Matrikula Masiboa",
    "Maximum Unit Load": "Gehieneko Karga",
    "Messages": "Mezuak",
    "Middle Name": "Bigarren Izena",
    "miscellaneous": "Bestelakoak",
    "Mobile": "Mugikorra",
    "Multi Departments": "Mintegi Anitzak",
    "Name": "Izena",
    "Nationality": "Nazionalitatea",
    "Next Activity Deadline": "Hurrengo Jardueraren Epemuga",
    "No of Person": "Pertsona kopurua",
    "Normal": "Normala",
    "Notes": "Oharrak",
    "Number of Departments": "Mintegi kopurua",
    "or": "edo",
    "Other": "Bestelakoa",
    "Parent": "Gurasoa",
    "Parent Admin": "Guraso Kudeatzailea",
    "Parent Course": "Goragoko Zikloa",
    "Parent Department": "Goragoko Mintegia",
    "Parent name": "Gurasoaren izena",
    "Parent Name": "Gurasoaren Izena",
    "Parent Term": "Goragoko Epealdia",
    "Parents": "Gurasoak",
    "Partner": "Kontaktua",
    "Personal Information": "Informazio Pertsonala",
    "Phone": "Telefonoa",
    "Practical": "Praktika",
    "Profile": "Profila",
    "Quantity": "Kantitatea",
    "Reason": "Arrazoia",
    "Reference": "Erreferentzia",
    "Registration Number": "Erregistro Zenbakia",
    "Registration Number must be unique per student!": "Erregistro zenbakia ikasle bakoitzeko bakarra izan behar da!",
    "Reject": "Ukatu",
    "Rejected": "Ukatua",
    "Related Company": "Enpresa Erlazionatua",
    "Related User": "Erlazionatutako Erabiltzailea",
    "Relation with Student": "Ikaslearekiko Harremana",
    "Relationships": "Harremanak",
    "Reporting": "Txostenak",
    "Reset to Draft": "Zirriborroetara Itzuli",
    "Responsible User": "Arduradun Erabiltzailea",
    "Roll Number": "Matrikula Zk.",
    "Roll Number & Student must be unique per Batch!": "Matrikula zenbakia eta ikaslea talde bakoitzeko bakarrak izan behar dira!",
    "Roll Number must be unique per Batch!": "Matrikula zenbakia talde bakoitzeko bakarra izan behar da!",
    "Running": "Abian",
    "Salesperson": "Saltzailea",
    "Self": "Bera",
    "Settings": "Ezarpenak",
    "Signature": "Sinadura",
    "SIS": "SIS",
    "Start Date": "Hasiera Data",
    "state": "egoera",
    "State": "Egoera",
    "Status": "Egoera",
    "Street": "Kalea",
    "Student": "Ikaslea",
    "Student Attendance Kiosk": "Ikasleen Presentzia Kiosk",
    "Student Course": "Matrikula",
    "Student Course Detail": "Matrikula Xehetasuna",
    "Student Course Details": "Matrikula Xehetasunak",
    "Student ID Card": "Ikasle Txartela",
    "Student IDCard": "Ikasle Txartela",
    "Student Leave": "Ikaslearen Baimena",
    "Student must be unique per Batch!": "Ikaslea talde bakoitzeko bakarra izan behar da!",
    "Student(s)": "Ikasle(ak)",
    "Students": "Ikasleak",
    "Subject": "Modulua",
    "Subject Management": "Moduluen Kudeaketa",
    "Subject Registration": "Modulu Erregistroa",
    "Subject Registration Analysis": "Modulu Erregistroaren Analisia",
    "Subject Registration Details": "Modulu Erregistroaren Xehetasunak",
    "subject registration graph": "Modulu Erregistroaren Grafikoa",
    "Subject Type": "Modulu Mota",
    "Subject Wise": "Moduluka",
    "Subject(s)": "Modulu(ak)",
    "Subjects": "Moduluak",
    "Submit": "Bidali",
    "Submitted": "Bidalita",
    "Tags": "Etiketak",
    "Tax ID": "IFZ",
    "Term Structure": "Epearen Egitura",
    "Terms": "Epeak",
    "Theory": "Teoria",
    "Three Trimesters": "Hiru Hiruhileko",
    "Timetable": "Ordutegia",
    "Timezone": "Ordu Eremua",
    "Title": "Izenburua",
    "Two Semesters": "Bi Seihileko",
    "Two Semesters subdivided by Quarters": "Bi Seihileko Hiruhilekoka",
    "Two Semesters subdivided by Quarters and Final Exams": "Bi Seihileko Hiruhilekoka eta Azken Azterketak",
    "Four Quarters": "Lau Hiruhileko",
    "Final Year Grades subdivided by Quarters": "Azken Urteko Notak Hiruhilekoka",
    "Type": "Mota",
    "Update parent email id first.": "Lehenik eguneratu gurasoaren helbide elektronikoa.",
    "User": "Erabiltzailea",
    "Users": "Erabiltzaileak",
    "Visa Info": "Bisa Informazioa",
    "Want to create user too ?": "Erabiltzailea ere sortu nahi duzu?",
    "Website": "Webgunea",
    "Year": "Urtea",
    "You cannot create recursive Course.": "Ezin duzu ziklo errekurtsiborik sortu.",
    "Zip": "Posta Kodea",
    "ZIP": "Posta Kodea",
    "Can not create parent multiple times.!": "Gurasoa ezin da aldiz bat baino gehiagotan sortu!",
    "Can not create relationship multiple times.!": "Harremana ezin da aldiz bat baino gehiagotan sortu!",
    "Facility": "Instalazioa",
    "Facility Lines": "Instalazio Lerroak",
    "Fees Access for Parents": "Tasak Gurasoei",
    "Fees On Duration": "Iraupenagatiko Tasak",
    "Fees On Session": "Saioagatiko Tasak",
    "Create Boolean": "Aukera Sortu",
    # Spanish → Basque
    "Alumnos matriculados": "Matrikulatutako Ikasleak",
    "Cargo de Profesor": "Irakasle Kargua",
    "Cargos": "Karguak",
    "Ciclo": "Zikloa",
    "Ciclos": "Zikloak",
    "Ciclos formativos": "Lanbide Zikloak",
    "Código": "Kodea",
    "Código de la huelga (irGREBA)": "Grebaren Kodea (irGREBA)",
    "Código interno del cargo (karguIZ)": "Karguaren Barne Kodea (karguIZ)",
    "El código de cargo debe ser único.": "Karguaren kodea bakarra izan behar da.",
    "El código de huelga debe ser único.": "Grebaren kodea bakarra izan behar da.",
    "El profesor titular y el sustituto deben ser personas distintas.": "Titularra eta ordezkoa pertsona desberdinak izan behar dira.",
    "Fecha": "Data",
    "Fecha fin": "Amaiera Data",
    "Fecha inicio": "Hasiera Data",
    "Gestión de Ciclos": "Zikloen Kudeaketa",
    "Grupo": "Taldea",
    "Grupos": "Taldeak",
    "Grupos donde imparte": "Irakasle den Taldeak",
    "Huelga de Profesores": "Irakasleen Greba",
    "Huelgas": "Grebak",
    "La fecha de fin no puede ser anterior a la fecha de inicio.": "Amaiera data ezin da hasiera baino lehenago egon.",
    "Motivo": "Arrazoia",
    "Nombre": "Izena",
    "Nº Matrícula": "Mat. Zk.",
    "Nº Participantes": "Parte-hartzaile Kop.",
    "Observaciones": "Oharrak",
    "Profesores": "Irakasleak",
    "Profesores participantes": "Parte-hartutako Irakasleak",
    "Profesor sustituto": "Ordezko Irakaslea",
    "Profesor titular": "Titular Irakaslea",
    "Sustitución de Profesor": "Irakasle Ordezkapenak",
    "Sustituciones (como sustituto)": "Ordezkapenak (ordezkoa bezala)",
    "Sustituciones (como titular)": "Ordezkapenak (titularra bezala)",
    # Already Basque - keep as-is
    "Amaiera": "Amaiera",
    "Amaiera data": "Amaiera data",
    "Artxibatua": "Artxibatua",
    "Artxibatutakoak": "Artxibatutakoak",
    "Bestelakoak": "Bestelakoak",
    "Departamentuak": "Mintegiak",
    "Ebaluazio mota": "Ebaluazio mota",
    "Ebaluazioa": "Ebaluazioa",
    "Egoera": "Egoera",
    "Epea": "Epea",
    "Erabiltzailea": "Erabiltzailea",
    "Gelak": "Gelak",
    "Greba": "Greba",
    "Grebak": "Grebak",
    "Guraso zikloa": "Guraso zikloa",
    "Hasiera": "Hasiera",
    "Hasiera data": "Hasiera data",
    "Helbidea": "Helbidea",
    "Hiruhilekoa": "Hiruhilekoa",
    "Hiruhilekoak": "Hiruhilekoak",
    "Hiruhilekoak Sortu": "Hiruhilekoak Sortu",
    "Hizkuntza": "Hizkuntza",
    "Ikasle Erabiltzailea Sortu": "Ikasle Erabiltzailea Sortu",
    "Ikaslea": "Ikaslea",
    "Ikasleak": "Ikasleak",
    "Ikasturtea": "Ikasturtea",
    "Ikasturteak": "Ikasturteak",
    "Informazio pertsonala": "Informazio pertsonala",
    "Irakasle Berria": "Irakasle Berria",
    "Irakasle titularra": "Irakasle titularra",
    "Irakaslea": "Irakaslea",
    "Irakasleak": "Irakasleak",
    "Irakasleen Grebak": "Irakasleen Grebak",
    "Irakasleen Karguak": "Irakasleen Karguak",
    "Irakasleen Ordezkapenak": "Irakasleen Ordezkapenak",
    "Kargua": "Kargua",
    "Karguak": "Karguak",
    "Konfigurazioa": "Konfigurazioa",
    "Lanbide zikloak": "Lanbide zikloak",
    "Matrikula xehetasunak": "Matrikula xehetasunak",
    "Matrikula zk.": "Matrikula zk.",
    "Matrikulak": "Matrikulak",
    "Matrikulatutako ikasleak": "Matrikulatutako ikasleak",
    "Mintegi nagusia": "Mintegi nagusia",
    "Mintegia": "Mintegia",
    "Mintegiak": "Mintegiak",
    "Modulua": "Modulua",
    "Moduluak": "Moduluak",
    "Mota": "Mota",
    "Nazionalitatea": "Nazionalitatea",
    "Odol taldea": "Odol taldea",
    "Oharrak": "Oharrak",
    "Ordezkapen bat": "Ordezkapen bat",
    "Ordezkapenak": "Ordezkapenak",
    "Ordezkatzaile irakaslea": "Ordezkatzaile irakaslea",
    "Ordezkoa": "Ordezkoa",
    "Ordezkoa bezala (beste bat ordeztuz)": "Ordezkoa bezala (beste bat ordeztuz)",
    "Parte-hartutako irakasleak": "Parte-hartutako irakasleak",
    "Parte-hartzaileak": "Parte-hartzaileak",
    "Parte-hartzaileen kop.": "Parte-hartzaileen kop.",
    "Taldea": "Taldea",
    "Taldeak": "Taldeak",
    "Taldekatu...": "Taldekatu...",
    "Titularra": "Titularra",
    "Titularra bezala (beste batek ordeztua)": "Titularra bezala (beste batek ordeztua)",
    "Zikloa": "Zikloa",
    "Zikloak": "Zikloak",
    "OpenEduCat": "OpenEduCat",
    "OpenEduCat Batch": "OpenEduCat Taldeak",
    "OpenEduCat Category": "OpenEduCat Kategoria",
    "OpenEduCat Course": "OpenEduCat Zikloak",
    "OpenEduCat Department": "OpenEduCat Mintegiak",
    "OpenEduCat Faculty": "OpenEduCat Irakasleak",
    "OpenEduCat Others": "OpenEduCat Bestelakoak",
}

def process_pot(pot_file, output_file):
    with open(pot_file) as f:
        content = f.read()

    # Update header
    content = content.replace(
        'POT-Creation-Date:',
        'PO-Revision-Date: 2026-05-09 00:00+0000\n"Language: eu_ES\n"POT-Creation-Date:'
    )
    content = content.replace('Last-Translator: \n', 'Last-Translator: CIFP Gizarte Berrikuntza\n')

    # Parse and replace msgstr values
    def replace_msgstr(m):
        msgid = m.group(1)
        clean_id = msgid.strip('"')
        translation = TRANSLATIONS.get(clean_id, '')
        if translation:
            return f'msgid {msgid}\nmsgstr "{translation}"'
        return m.group(0)

    # Replace simple single-line msgid/msgstr pairs
    content = re.sub(
        r'msgid ("(?:[^"\\]|\\.)*")\nmsgstr ""',
        replace_msgstr,
        content
    )

    with open(output_file, 'w') as f:
        f.write(content)

    # Count filled translations
    filled = len(re.findall(r'msgstr "(?!")[^"]+', content))
    total = len(re.findall(r'\nmsgid "(?!")[^"]+', content))
    print(f"Filled {filled} of {total} translations")

process_pot(
    '/home/erp/openeducat-project/openeducat_eu.pot',
    '/home/erp/openeducat-project/addons19/openeducat_erp/openeducat_hernani/i18n/eu_ES.po'
)
