from . import op_kargu
from . import op_kargu_mintegi
from . import op_perfilazio_kargu
from . import op_greba
from . import op_ordezkapen
from . import op_faculty_ext
from . import op_student_ext
from . import op_batch_ext
from . import op_department_ext
from . import op_report
from . import op_subject_banaketa
from . import op_apoyo_taldea
from . import op_subject_ext
from . import op_perfilazio_bertsioa
from . import op_classroom_ext
from . import op_fet_constraints
